#!/bin/bash

# should add a check for a valid colon

colon=`echo $1 | grep -c ':'`
if [ $colon -eq 0 ]
then
    echo "usage: get [user@]hostname:path"
    exit
fi

thing=`echo $1 | cut -d: -f2`
host=`echo $1 | cut -d: -f1`

curdir=`pwd`
home=$HOME

# want to remove home from curdir:

reldir=`echo $curdir | sed -e s+$HOME/++`

# this is more complicated than I anticipated, what if
# for instance I had done get host:myfile*/otherdir*/*.pdf
# That's gonna get screwy...
#things_to_fetch=`ssh $host "ls -d ~/$reldir/$thing"`
#dirnames=$(for f in $things_to_fetch; do dirname $f; done | sort | uniq)

if [ ! -d `dirname $thing` ]
then
    mkdir -p `dirname $thing`
fi


scp -r $host:~/$reldir/$thing `dirname "$thing"`/
